### ISSUE TITLE
Homework Feedback JS1-Week1

### ISSUE THREAD

**Issue by Swapna-Sahu** [myshuker/hyf-homework#3]
Hi ,
Great job 🥇 . Everything looks fine for me. I can see you used "let" that's good. 

Task - Goodboy-Oldboy (A dog age calculator)
I think you have not noticed the logic for dog year age calculation : " string out: "Your dog will be 10 human years old in 2027" or "Your dog will be 70 dog years old in 2027 ". Use this logic.

Task - House price estimator
Line 67 and Line 70 - you wrote console.loge instead of console.log . That is why you are getting error.

Task - Starup name generator
Code is prefect but I was wondering why did you wrote 8 instead of 10. 

Rest everything looks good to me. Keep it up.

**Comment by myshuker** [comment]
Hey Swapna ...
Thanks for your effort to at look on our homework ....
I made the reparation in my homework but I soory meby the secound note dosent correct coz I dont catch the meaning in the task , actually I dont understand what that mean in reality....(the relation betwen dogs year and human years...)...maby if I understand the meaning of the task i will do it correct .....
thanks for advanced
best regards
Mohammad
