### ISSUE TITLE
Homework Feedback JS1- Week3

### ISSUE THREAD

**Issue by Swapna-Sahu** [myshuker/hyf-homework#5]
Good Work 👍 . Good to see you are trying different way.  Here is  solution for your problems : 

FavSong Task -
function getSongByTitle(title) {
  var songTitle = title;
  var databaseLength = songDatabase.length;
  for (i = 0; i < databaseLength; i++) {
    if (songDatabase[i].title === songTitle) {
      position = i;
      console.log(songDatabase[i]);
      return position;
      break;
    }
  }
  console.log("Title do not match");
  return;
}

Fuzzy Search - means that even if user will give half title name then also it should show the song object ex - "Girls Like You" , he can write "Girls Like “.

**Comment by myshuker** [comment]
i tried to repair it  without break function ...but its still dosent work ....

function getSongByTitle (title){               
    for ( let i=0; i<songDatabase.length; i++){    
         if (title === songDatabase[i].title){       // searching about song listed in hte data base
              searchedSong.push( songDatabase[i]);
              console.log(searchedSong);
              
       } else if (title !== songDatabase[i].title){          // searching about song doesnt listed in hte data base
    console.log("there are no song match this title");  
} 
}
}

//getSongByTitle("Girls Like You");  // IT DOSENT WORK BUT I DONT KNOW 😭😭😭😭
//getSongByTitle("Shape of You"); // IT DOSENT WORK BUT I DONT KNOW 😭😭😭😭
//getSongByTitle("My baby"); // IT DOSENT WORK BUT I DONT KNOW 😭😭😭😭
//getSongByTitle("Who do you love");   // this work now
