### ISSUE TITLE
Homework Feedback JS1-Week4

### ISSUE THREAD

**Issue by Swapna-Sahu** [myshuker/hyf-homework#6]
Great work 🥇 . But i have few comment to modify. Sorry for late feedback 

Here is your feedback - 

command.includes("Add") && command.includes("fishing") and command.includes("Remove" && "fishing")

Not every task is for fishing / you can have different task instead you can write “ my todo” and you can remove below code
if (command.includes("Add") && command.includes("singing") ) {
todos.push("singing in the shower")
return ("fishing added to your todo");
}

Line 19 and line 87 
Both condition is same . 
So instead of Line 87 , you can check if inputs are number

For timer task - I am not sure if it is working
U mentioned return(Timer Done) but where it should show. You can write alert inside of return

**Comment by myshuker** [comment]
for line 87 I cant use isNaN here to chack is the input number or not because when commandSplit split the input definded it as string .... because the input doesnt have just number but also string

**Comment by myshuker** [comment]
and  for the line 19 and line 87.... is it hte same??? I know ("") mean =>> empty 
but (" ")mean =>>  there are space in the input...... is that right ?...sorry Im still new in the field

**Comment by myshuker** [comment]
and for timer task I wrote the setTimeout( myFunction, toMilliSecond) it will invok the function myfunction after the 4mintus passed

**Comment by Swapna-Sahu** [comment]
Line 87 
(typeof (command) === typeof (5) && (command !== null))  or
command.includes('+') || command.includes('*') || command.includes('-')

**Comment by Swapna-Sahu** [comment]
Q - For the line 19 and line 87.... is it the same??? 
Write the below command in console and check what they mean : 
let a = "";
let b =" ";
console.log("type of a =", typeof a);
console.log("type of b =", typeof b);

**Comment by Swapna-Sahu** [comment]
For timer task : 
yes, the function is correct but when it call the function it return the string "Timer done". Are you getting the output ?because the task is after the time up you need to show this output.
either you do this 
console.log('Timer done');
or 
alert('Timer done');

make sense?

**Comment by myshuker** [comment]
for the timer i tried with 6 secound fx. just to get the output quickly not 4 minuts and print the result with console.log("timer done") then I get the output after 6 sec ...is that mean the code is right?

**Comment by myshuker** [comment]
thanks for help....and advise
